### ISSUE TITLE
redux-immutable support

### ISSUE THREAD

**Issue by stepankuzmin** [logux/redux#7] opened 2018-03-05 12:40 UTC
Is seems that there is a problem with replacing reducer when using `redux-immutable`. Consider example:

```js
import createLoguxCreator from 'logux-redux/create-logux-creator';
import { combineReducers } from 'redux-immutable';
const reducer = combineReducers({});

const createStore = createLoguxCreator({
  subprotocol: '1.0.0',
  server: 'ws://127.0.0.1:1337',
  userId: 10
});

const store = createStore(reducer);
```

This fails with error that `...previous state received by the reducer is of unexpected type. Expected argument to be an instance of Immutable.Collection or Immutable.Record...` pointing to https://github.com/logux/logux-redux/blob/master/create-logux-creator.js#L155

**Comment by ai** [comment] 2018-03-05 12:42
Thanks for report. I will investigate it in the end of the week (sorry, really hard well because if moving to NY).

**Comment by ai** [comment] 2018-07-17 21:53
I started 0.3 where I plan to fix the problem by design

**Comment by ai** [comment] 2020-05-27 04:44
I think we version should support it

**Closed by ai** 2020-05-27 04:44 UTC
